### ISSUE TITLE
Bad URL to artifact uploaded

### ISSUE THREAD

**Issue by germanzero** [ruediste/mvnzone#1]
Hi, when an artifact is uploaded, the URL attached to the DOWNLOAD button in the artifacts page (https://www.mvnzone.net/artifacts/artifacts) is wrong... 

Wrong URL attached: 
https://repo.mvnzone.net/repocom/github/germanzero/Upstream/1.0-SNAPSHOT/Upstream-1.0-20170307.201639-1.jar

The correct URL must be: 
https://repo.mvnzone.net/repo/com/github/germanzero/Upstream/1.0-SNAPSHOT/Upstream-1.0-20170307.201639-1.jar

The word "repocom" is wrong, really should say "repo/com".
Thanks and good luck.

**Comment by ruediste** [comment]
Thanks for pointing out, you are right. Will do a fix in the coming days. This should not affect download via maven, luckily.

**Comment by ruediste** [comment]
Just deployed the bugfix to production. URLs look good now.
